services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python cli.py
    volumes:
      - .:/app
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER=${AZURE_STORAGE_CONTAINER}