services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m undpstac_pipeline.cli daily -y 2024 -m 1 -d 25  -f
    volumes:
      - .:/app
      - /tmp:/tmp
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - user=1000
