services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m nighttimelights_pipeline.cli daily -y 2024 -m 1 -d 25 -f
    volumes:
      - .:/app
      - /tmp:/tmp
