import os
from enum import Enum
ROOT_EOG_URL = 'https://eogdata.mines.edu/nighttime_light/nightly/'

class DNB_FILE_TYPES(Enum):
    DNB = 'DNB'
    DNB_SUNFILTERED = 'DNB_SUNFILTERED'
    CLOUD_COVER = 'CLOUD_COVER'

DNB_FOLDER = 'rade9d'
DNB_SUNFILTERED_FOLDER = 'rade9d_sunfiltered'
DNB_CLOUD_COVER_FOLDER = 'cloud_cover'
DNB_BASE_TEMPLATE = 'SVDNB_npp_d{date}'
DNB_TEMPLATE = f'{DNB_BASE_TEMPLATE}.rade9d.tif'
DNB_SUNFILTERED_TEMPLATE= f'{DNB_BASE_TEMPLATE}.rade9d_sunfiltered.tif'
DNB_CLOUD_COVER_TEMPLATE = f'{DNB_BASE_TEMPLATE}.vcld.tif'

FILE_TYPE_FOLDERS = {DNB_FILE_TYPES.DNB:DNB_FOLDER, DNB_FILE_TYPES.DNB_SUNFILTERED:DNB_SUNFILTERED_FOLDER, DNB_FILE_TYPES.CLOUD_COVER:DNB_CLOUD_COVER_FOLDER}
FILE_TYPE_TEMPLATES = {DNB_FILE_TYPES.DNB:DNB_TEMPLATE, DNB_FILE_TYPES.DNB_SUNFILTERED:DNB_SUNFILTERED_TEMPLATE, DNB_FILE_TYPES.CLOUD_COVER:DNB_CLOUD_COVER_TEMPLATE}
FILE_TYPE_NAMES = set(FILE_TYPE_FOLDERS)

AZURE_CONTAINER_NAME = 'stacdata'
AZURE_DNB_COLLECTION_FOLDER = 'nighttime-lights'
AZURE_STORAGE_CONNECTION_STRING = os.environ.get('AZURE_STORAGE_CONNECTION_STRING')
COG_CONVERT_TIMEOUT= os.environ.get('COG_CONVERT_TIMEOUT', 1800)
AIOHTTP_READ_CHUNKSIZE = os.environ.get('AIOHTTP_READ_CHUNKSIZE',1024**2*4) # 4MB

STAC_CATALOG_NAME = 'catalog.json'
STAC_COLLECTION_NAME = 'collection.json'